### PR TITLE
Bounties/188

### PR DESCRIPTION
**Pull request by bshyong**
hey @josiasds I rebased against master and added some changes today FYI
Thanks for all the work so far on it!

### CODE REVIEW

**Comment by bshyong** [comment]
Copying the list here for clarity
- [x] remove not-null constraints on some fields that are no more required
- [x]  generate shortcode for every uploaded image
- [x] generate short URL for uploaded images
- [x] fetch image and save to the S3 bucket when original_source is sent by the user
- [x]  move image processing to background job
- [x] Use fingerprinting so that files that are already uploaded will be ignored https://github.com/thoughtbot/paperclip#md5-checksum--fingerprint
- [x] each uploaded .gif should also have an associated mp4 so that we can serve the video version to the client
- [x] include flag for offensive content
- [x] add scope so Images returned to client apps must have an attached gif or mp4
- [x] change size scopes to look at file sizes instead of byte column
- [ ]  actually convert gifs to mp4 in a background job an associate them with the original image
- [ ] add amazon cloudfront
- [x] fetch attached gifs & mp4s for all existing images in the DB
- [x] Remove non-null restriction on name/caption

**Comment by bshyong** [comment]
If you have time to help out, let me know

**Comment by josiasds** [comment]
Awesome @bshyong! :beers:

**Comment by adrianonco** [comment]
Wow man, what an advance both made here!!!  (applauses) Thanks!!!

**Pull request merged**
